name: auto-update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  auto-update:
    runs-on: macos-latest
    env:
      RUN_ENV: "github"
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: brew install ack
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: run
        run: bash update.sh
